image: docker:latest

before_script:
  - docker info
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA

build:
  stage: build
  tags:
    - docker
  except:
    - master
    - tags
  script:
    - docker build -t $IMAGE_TAG .

deploy:
  stage: deploy
  tags:
    - docker
  only:
    - master
    - tags
  script:
    - if [[ "$CI_COMMIT_REF_SLUG" == "master" ]] ; then TAG=latest ; else TAG=$CI_COMMIT_REF_SLUG ; fi
    - RELEASE_IMAGE_TAG=$CI_REGISTRY_IMAGE:$TAG
    - docker build -t $IMAGE_TAG .
    - docker tag $IMAGE_TAG $RELEASE_IMAGE_TAG
    - docker push $RELEASE_IMAGE_TAG
